### ISSUE TITLE
Update Visitor Details

### ISSUE THREAD

**Issue by Reaction77** [livechat/api-client-csharp#1]
I am attempting to use the livechat API to add custom visistor details as described here: https://developers.livechatinc.com/rest-api/#add-custom-visitor-details

When I use the Visitors.AddCustomDetails() method it returns "{\"result\":\"Visitor details added\"}" however the fields are not displayed when viewing the visitor on the web portal.

I fields are also not visible on the visitor when returned from the Visitors.List() method.

Please could you advise.

Thanks,
Chris Fitz-Avon

**Comment by krzysztof-gorski** [comment]
Sorry for delay. I was able to reproduce described situation. I will investigate this issue and get back to you as soon we find a solution to this problem.

**Comment by krzysztof-gorski** [comment]
The fields were formatted incorrectly in Visitors.AddCustomDetails(). It has been fixed.
See commit: https://github.com/livechat/api-client-csharp/commit/47636ffcdea4a8c3db647fb97b7b1cc0304d5077

Right now the visitor details are properly displayed in web application, however they are still not returned by Visitors.List() method. This issue is under investigation.

**Comment by Reaction77** [comment]
Nice one, that has worked, Thanks for the updates! 

Seeing the updated visitor in the web application was my primary concern. Would you like me to leave this issue open whilst you investigate the Visitors.List() method?

**Comment by krzysztof-gorski** [comment]
I'm glad it helped. Leave the issue open until we fix the Visitors.List() method.

**Comment by krzysztof-gorski** [comment]
It seems that the mapping for `details` in `visitor` object in API is missing. It will be fixed within few days.

**Comment by krzysztof-gorski** [comment]
It has been fixed. 

Thank you for posting this issue and sorry that fixing it took so long.
